# Generated by Django 4.2.2 on 2023-07-18 13:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("user_ordinary", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserChat",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nick", models.CharField(max_length=30)),
                ("remark", models.CharField(blank=True, max_length=100, null=True)),
                ("file", models.FileField(blank=True, null=True, upload_to="")),
                (
                    "user_chat",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("recipient", models.CharField(max_length=30)),
                ("is_active", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(null=True)),
                ("modified_at", models.DateTimeField(null=True)),
                (
                    "or_chat",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user_ordinary.userordinary",
                    ),
                ),
            ],
        ),
    ]
