# Generated by Django 4.2.2 on 2023-07-22 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("user_privileged", "0001_initial"),
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userchat",
            name="pr_chat",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="user_privileged.userprivileged",
            ),
        ),
    ]
