# Generated by Django 4.2.2 on 2023-06-21 11:04

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserPrivileged",
            fields=[
                (
                    "user_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("nickname", models.CharField(max_length=30)),
                ("mail", models.EmailField(max_length=120, unique=True)),
                (
                    "file",
                    models.FileField(blank=True, null=True, upload_to="auth_photo/"),
                ),
                ("email_verified", models.BooleanField(default=False)),
                (
                    "created_at",
                    models.DateTimeField(null=True, verbose_name="Date of creation"),
                ),
                (
                    "modified_at",
                    models.DateTimeField(null=True, verbose_name="Date of change"),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            bases=("auth.user",),
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
